defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: <%= ENV['MYSQL_HOST'] || 'localhost'%>

development:
  <<: *defaults
  database: vc_playground_development

test:
  <<: *defaults
  database: vc_playground_test
  pool: 1
